### ISSUE TITLE
ERRO[0003] GoError: Failed to create schema., OriginalError: %!w(srclient.Error={42201 Invalid schema {subject=msk.ipace-dev.comptest.topic.internal.any.v1-value,version=0,id=-1,schemaType=JSON,references=[],schema={"title":"Value","type":"object","properties":{"templateId":{"type":"int","description":"TemplateId."},"testId":{"type":"int","description":"TestId."},"status":{"type":"string","description":"Status."},"message":{"type":"string","description":"Message."}}}} 0x14002e64d80})         at github.com/mostafa/xk6-kafka.(*Kafka).schemaRegistryClientClass.func2 (native)         at file:////dev_latest/t.js:166:56(211) 

### ISSUE THREAD

**Issue by arpitaso** [mostafa/xk6-kafka#239]
@mostafa, i am using a schemaregistry with url and basic auth, on running the script i get the below error.
I don't see any difference in the previous schema and the current schema.

kindly help here

`import {
    LoadJKS,
    TLS_1_2
} from "k6/x/kafka";
import {
    Writer,
    Reader,
    Connection,
    SchemaRegistry,
    SCHEMA_TYPE_JSON,
    SASL_SCRAM_SHA512,  KEY,
                         VALUE,TOPIC_NAME_STRATEGY,
} from "k6/x/kafka";
import VaultManager from './VaultManager.js';

export let options = {
    stages: [{
            target: 1,
            duration: '30s'
        }
    ],
};

export const vault = new VaultManager('Tech Ops Platform', 'DEV');

let offset = -1;
// partition and groupId are mutually exclusive
let partition = 0;
let numPartitions = 1;
let replicationFactor = 1;

let username = "";
let password = "";
let passwordToAccessTrustore = "";
let saslConfig = {};

let writer;
let reader;
let connection;

export function setup() {
    console.log('Inside setup function ');
       username= "username",
        password= "password",
        passwordToAccessTrustore="passwordToAccessTrustore"

}

export function initializeCredentials() {
    console.log('Inside initializeCredentials function');
    if (!username || !password || !passwordToAccessTrustore) {
  username= "pp.ipacedev.v1",
          password= "IuM0MujbAEfG",
          passwordToAccessTrustore="nxs9a08DskoOpas2d34lwEs"

        saslConfig = {
            username: username,
            password: password,
            algorithm: SASL_SCRAM_SHA512
        };
    }
}
const trustStoreUrl = vault.getIPaceEnvConfig().getValueFromEnvFor('ROOTDIR')+'/truststore.jks';

export default function(data) {
    initializeCredentials();

const jks = LoadJKS({
        path: trustStoreUrl,
        password: passwordToAccessTrustore,
        clientCertAlias: "retina-kafka",
        clientKeyAlias: "retina-kafka",
        clientKeyPassword: passwordToAccessTrustore,
        serverCaAlias: "ca-1",
    });
const tlsConfig = {
  enableTls: true,
  insecureSkipTlsVerify: false,
  minVersion: TLS_1_2,

  // The certificates and keys can be loaded from a JKS keystore:
  // clientCertsPem is an array of PEM-encoded certificates, and the filenames
  // will be named "client-cert-0.pem", "client-cert-1.pem", etc.
  // clientKeyPem is the PEM-encoded private key and the filename will be
  // named "client-key.pem".
  // serverCaPem is the PEM-encoded CA certificate and the filename will be
  // named "server-ca.pem".
   clientCertPem: jks["clientCertsPem"][0], // The first certificate in the chain
   clientKeyPem: jks["clientKeyPem"],
   serverCaPem: jks["serverCaPem"],
// clientCertPem : clientCertPem,
// clientKeyPem : clientKeyPem,
// serverCaPem : serverCaPem
};

    const brokers = ["digital.net:443"];
    const topic = "internal.any.v1";

const BasicAuth= {
 username: "pp.ipacedev.v1",
 password: "IuM0MujbAEfG",
}

//    const schemaRegistry = new SchemaRegistry();
const schemaRegistry = new SchemaRegistry({
    url: "https://pp-west-2-shared-emp-kafka-sr.maersk-digital.net",
    basicAuth: BasicAuth,
    tls: tlsConfig
});

const keySchema = JSON.stringify({
  title: "Key",
  type: "object",
  properties: {
    correlationId: {
      type: "string",
      description: "A key.",
    },
  },
});
console.log("keySchema", keySchema);

              let templateId= 5;
              let  testId= 4;
              let  status= "deactive";
              let  message= "Hi, I am testing";
const valueSchema = JSON.stringify({
  title: "Value",
  type: "object",
  properties: {
    templateId: {
      type: "int",
      description: "TemplateId.",
    },
    testId: {
      type: "int",
      description: "TestId.",
    },
     status: {
          type:  "string",
          description: "Status.",
     },
     message: {
         type: "string",
         description: "Message.",
     },
  },
});

console.log("valueSchema", valueSchema);

const keySubjectName = schemaRegistry.getSubjectName({
  topic: topic,
  element: KEY,
  subjectNameStrategy: TOPIC_NAME_STRATEGY,
  schema: keySchema,
});

console.log("keySubjectName", keySubjectName);
const valueSubjectName = schemaRegistry.getSubjectName({
  topic: topic,
  element: VALUE,
  subjectNameStrategy: TOPIC_NAME_STRATEGY,
  schema: valueSchema,
});
console.log("valueSubjectName", valueSubjectName);
const keySchemaObject = schemaRegistry.createSchema({
  subject: keySubjectName,
  schema: keySchema,
  schemaType: SCHEMA_TYPE_JSON,
});

const valueSchemaObject = schemaRegistry.createSchema({
  subject: valueSubjectName,
  schema: valueSchema,
  schemaType: SCHEMA_TYPE_JSON,
});

    writer = new Writer({
        brokers: brokers,
        topic: topic,
        sasl: saslConfig,
        partition: partition,
        tls: tlsConfig,
    });

    reader = new Reader({
        brokers: brokers,
        topic: topic,
        partition: partition,
        offset: offset,
        sasl: saslConfig,
        tls: tlsConfig,
    });

    connection = new Connection({
        address: brokers[0],
        sasl: saslConfig,
        tls: tlsConfig,
    });
    let messages = [{
        key: schemaRegistry.serialize({
            data: {
                correlationId: "test-id-abc-" + 1,
            },
              schema: keySchemaObject,
            schemaType: SCHEMA_TYPE_JSON,
        }),
        value: schemaRegistry.serialize({
            data: {
                templateId: 5,
                testId: 4,
                status: "deactive",
                message: "Hi, I am testing",
            },
                schema: valueSchemaObject,
            schemaType: SCHEMA_TYPE_JSON,
        }),
    }];
    console.log("message", messages);

    writer.produce({
        messages: messages,
    });

    let mesg = reader.consume({
        limit: 10,
    });

//    console.log("correlation=====>>>", schemaRegistry.deserialize({
//        data: mesg[0].key,
//        schemaType: SCHEMA_TYPE_JSON,
//    }).correlationId);

    console.log("schema------>>>>>", schemaRegistry.deserialize({
        data: messages[0].value,
        schemaType: SCHEMA_TYPE_JSON,
    }));
}

export function teardown() {
    if (writer) writer.close();
    if (reader) reader.close();
    if (connection) connection.close();
}
`

error

`ERRO[0003] GoError: Failed to create schema., OriginalError: %!w(srclient.Error={42201 Invalid schema {subject=msk.ipace-dev.comptest.topic.internal.any.v1-value,version=0,id=-1,schemaType=JSON,references=[],schema={"title":"Value","type":"object","properties":{"templateId":{"type":"int","description":"TemplateId."},"testId":{"type":"int","description":"TestId."},"status":{"type":"string","description":"Status."},"message":{"type":"string","description":"Message."}}}} 0x14002e64d80})
        at github.com/mostafa/xk6-kafka.(*Kafka).schemaRegistryClientClass.func2 (native)
        at file:///Users/arpita.sood/Documents/Maersk_code/sre-perf-ls-test-demo/dev_latest/t.js:166:56(211) `

**Comment by mostafa** [comment]
@arpitaso 

I digged into the srclient and schema registry code and found [this line](https://github.com/confluentinc/schema-registry/blob/2dcbfc66c50e8b31fec6f37988106a67e2373a55/core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java#L1403) that raises the `42201 Invalid schema ...` error. This points to [this line](https://github.com/confluentinc/schema-registry/blob/master/json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaProvider.java#L35) and it seems that your schema is somehow invalid. Look at the logs of your schema registry server to see why it fails.

**Comment by mostafa** [comment]
Hey,

I suppose your question is answered, I'll close this issue. If you have further questions related to the same issue, please re-open this, otherwise open a new one.
